services:
  jupyter:
    build:
      context: ..
      dockerfile: .devcontainer/jupyter/Dockerfile
    container_name: mi25a003_pytorch_jupyter
    working_dir:  /home/jovyan/work
    volumes:
      # ホストのルートをコンテナの /workspace にマウントする設定例
      - ../jupyter:/home/jovyan/work
    ports:
      - "8888:8888"
    # GPU設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    shm_size: '12gb'
    command: sleep infinity
    stdin_open: true
    tty: true